name: Test My Containers Implemitation CI

on:
   push:
      branches: ["main"]
      
jobs:
   build-and-test:
      runs-on: ubuntu-latest
      steps:
      - name: Download source code
        uses: actions/checkout@v6
        
      - name: Install Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
        
      - name: Go run
        run: go run main.go