name: Test My Containers Implementation CI

on:
   push:
      branches: ["main"]
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: make build

      - name: Setup rootfs
        run: make setup-rootfs

      # - name: Lint
      #   run: make lint

      - name: Run tests
        run: make test

      - name: Test summary
        uses: test-summary/action@v2
        with:
          paths: test-results.xml
        if: always()
